DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email     VARCHAR(50) DEFAULT NULL
);
